plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = '1.0.0.3'
group = 'io.github.derexxd'

base {
    archivesName = 'squidimprovements-1.21'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.251'

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        squidimprovements {
            sourceSet(sourceSets.main)
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
