modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "squidimprovements"
version = "1.0.0.3"
displayName = "Squid Improvements"
displayURL = "https://www.derekchen.dev/"
authors = "DerexXD"
description = '''Squids and Glow Squids get quality of life, vanilla friendly upgrades!'''

[[dependencies.squidimprovements]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.251,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.squidimprovements]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"
